const DUMMY_PRODUCTS = [
  {
    name: 'CTM REIN 1.0 (27,5") matná petrolejová / oranžová 19"',
    picture: '',
    price: '19 224',
    sleva: true,
    top: false,
    novinka: false,
  },
  {
    name: 'VT-BIKE SPYDER 24" černá mat / zelená',
    picture: '',
    price: '19 224',
    sleva: false,
    top: true,
    novinka: false,
  },
  {
    name: 'GALAXY EARLY BIRD 20" ČERNÝ',
    picture: '',
    price: '19 224',
    sleva: false,
    top: false,
    novinka: true,
  },
  {
    name: 'GALAXY PYXIS 20" ČERNÁ',
    picture: '',
    price: '19 224',
    sleva: true,
    top: true,
    novinka: true,
  },
  {
    name: 'CTM REIN (27,5") matná petrolejová / oranžová 19"',
    picture: '',
    price: '19 224',
    sleva: true,
    top: true,
    novinka: true,
  },
  {
    name: 'Dema TIGRA 3 SVĚTLÉ ŠEDÁ/ ČERVENÁ"',
    picture: '',
    price: '19 224',
    sleva: true,
    top: true,
    novinka: true,
  },
];
